### PR TITLE
Fix accidental double-close of fds

### LINKED ISSUE #3038: Failed to resize shmem (EBADF)
@vtjnash reports the following:
```
[FATAL /workspace/srcdir/rr/src/util.cc:814:resize_shmem_segment() errno: EBADF] Failed to resize shmem to 104
--
  | === Start rr backtrace:
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr13dump_rr_stackEv+0x28)[0x5b6dc8]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr15notifying_abortEv+0x47)[0x5bb897]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr[0x5fd712]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr7Session18create_shared_mmapERNS_18AutoRemoteSyscallsEmNS_10remote_ptrIvEEPKciiOSt10shared_ptrINS_21MonitoredSharedMemoryEE+0x162)[0x5cf0e2]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr12AddressSpace17post_exec_syscallEPNS_4TaskE+0xb1)[0x4ddf91]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr4Task17post_exec_syscallEv+0x25)[0x591c85]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr[0x524da7]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr[0x5c4e44]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr19rec_process_syscallEPNS_10RecordTaskE+0x155)[0x558cb5]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr13RecordSession21syscall_state_changedEPNS_10RecordTaskEPNS0_9StepStateE+0x917)[0x53eca7]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr13RecordSession11record_stepEv+0x481)[0x541eb1]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x9f4)[0x533714]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr(main+0x276)[0x4c2a06]
  | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea)[0x7f993d2f0d0a]
  | /root/.julia/artifacts/c15b91caba48cf253fe8f6dbdafbe18446c849c1/bin/rr[0x4c2e3e]
  | === End rr backtrace
```

From https://buildkite.com/julialang/julia-master/builds/7522#f6e230fc-db36-4d7e-982f-2d7c5cfb27c5.

I don't think we've seen this before. As with #3037, this is a recently upgraded rr, so this may also be a regression. Looking into it.

### PR DESCRIPTION
**Pull request by Keno**
`ScopedFd` has implicit conversions to and from `int`. This is
very dangerous, because patterns like:
```
void f(ScopedFd &fd) {}
void g(int fd) { f(fd); }
void h(ScopedFd &fd) { g(fd); }
```
will compile without complaint, but will actually introduce an
additional `::close` call due to the implicitly constructed
`ScopedFd`. There were a number of instances of this issue
in the codebase. Try to prevent this from happening again
in the future by making the ScopedFd constructor explicit.

Should fix #3038

### CODE REVIEW

File: src/ScopedFd.h [hunk 1]
```diff
@@ -17,7 +19,6 @@ namespace rr {
 class ScopedFd {
 public:
   ScopedFd() : fd(-1) {}
-  ScopedFd(int fd) : fd(fd) {}
```
Comment (vtjnash) [inline src/ScopedFd.h:20]:
```c++
    explicit ScopedFd(int fd) : fd(fd) {}
```
Keno wanted me to mention that this constructor could also be kept, with the `explicit` keyword to prevent it from being quite as easily called unintentionally. It still has a few more cases, IIRC, where this could get used unintentionally, but it cuts down on the worse of the issues.

Comment (Keno) [reply src/ScopedFd.h:20]: @rocallahan can say which he prefers. I think either is fine. Using `explicit` is certainly a smaller change. (I would have used it, but I failed to remember what it was called).

Comment (rocallahan) [reply src/ScopedFd.h:20]: I think making the constructor `explicit` is the right approach here. We probably should avoid non-explicit 1-arg constructors everywhere. It's a design error in C++ that single-arg constructors are used as implicit conversions by default.

**Comment by Keno** [comment]
Updated to use `explicit`.
