### PR TITLE
Print a useful error message if we can't interpose libstdc++ symbols correctly because the library was likely loaded with RTLD_LOCAL.

### LINKED ISSUE #3304: Segmentation fault with std::random_device (rr 5.5.0 and master)
I'm trying to use rr 5.5.0 with [Horovod](https://github.com/horovod/horovod), a Python extension written in C++. However, `rr record` crashes with SIGSEGV when I let python import the module. The segmentation fault happens when a `std::random_device` is constructed, which triggers some overload provided by rr. I've seen that there is some history of problems with `std::random_device`, e.g. #2459.

Related Horovod source: https://github.com/horovod/horovod/blob/v0.25.0/horovod/common/optim/bayesian_optimization.h#L102

Environment notes:
``` bash
$ grep -m 1 'model name'  /proc/cpuinfo
model name      : AMD EPYC 7302 16-Core Processor

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

$ uname -r
5.8.0-44-generic

$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ python --version
Python 3.9.13

$ rr --version  # installed from https://github.com/rr-debugger/rr/releases/download/5.5.0/rr-5.5.0-Linux-x86_64.deb
rr version 5.5.0
```

Reproducer:
```
$ python -m venv horovod-rr
$ source horovod-rr/bin/activate
$ pip install tensorflow==2.6.5
$ pip install horovod==0.25.0    # Horovod is compiled locally when installing the package

$ rr record python -c 'import horovod.tensorflow as hvd'
rr: Saving execution to trace directory `.../.local/share/rr/python-11'.
Segmentation fault

$ rr replay
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.9...
(No debugging symbols found in /usr/bin/python3.9)
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:27655
Reading symbols from /lib64/ld-linux-x86-64.so.2...
(No debugging symbols found in /lib64/ld-linux-x86-64.so.2)
0x00007f9d758a1100 in ?? () from /lib64/ld-linux-x86-64.so.2
(rr) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(rr) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f9d756944b4 in _ZNSt13random_device7_M_initERKSs (this=0x52df178, token=0x7ffc65d692c0)
    at /home/roc/rr/rr/src/preload/overrides.c:251
#2  0x00007f9d2e0680ef in std::random_device::random_device (this=0x52df178) at /usr/include/c++/9/ext/new_allocator.h:80
#3  horovod::common::BayesianOptimization::BayesianOptimization (this=0x52df150, bounds=std::vector of length 2, capacity 2 = {...},
    alpha=0.80000000000000004, xi=<optimized out>)
    at /tmp/pip-install-5bm_d0w5/horovod_eec816e9995d41e8a0bdb2d1f5865572/horovod/common/optim/bayesian_optimization.cc:59
#4  0x00007f9d2e0448bf in horovod::common::ParameterManager::BayesianParameter::ResetBayes (
    this=0x7f9d31980d08 <horovod::common::(anonymous namespace)::horovod_global+58721512>) at /usr/include/c++/9/bits/stl_uninitialized.h:82
#5  0x00007f9d2e044ea8 in horovod::common::ParameterManager::BayesianParameter::BayesianParameter (
    this=0x7f9d31980d08 <horovod::common::(anonymous namespace)::horovod_global+58721512>, variables=..., test_points=..., max_samples=20,
    gaussian_process_noise=0.80000000000000004)
    at /tmp/pip-install-5bm_d0w5/horovod_eec816e9995d41e8a0bdb2d1f5865572/horovod/common/parameter_manager.cc:409
#6  0x00007f9d2e045d1e in horovod::common::ParameterManager::ParameterManager (
    this=0x7f9d31980c10 <horovod::common::(anonymous namespace)::horovod_global+58721264>) at /usr/include/c++/9/bits/stl_uninitialized.h:82
#7  0x00007f9d2e005b4a in horovod::common::HorovodGlobalState::HorovodGlobalState (
    this=0x7f9d2e180820 <horovod::common::(anonymous namespace)::horovod_global>) at /usr/include/c++/9/bits/atomic_base.h:279
#8  __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535)
    at /tmp/pip-install-5bm_d0w5/horovod_eec816e9995d41e8a0bdb2d1f5865572/horovod/common/operations.cc:116
#9  _GLOBAL__sub_I_operations.cc(void) ()
    at /tmp/pip-install-5bm_d0w5/horovod_eec816e9995d41e8a0bdb2d1f5865572/horovod/common/operations.cc:1879
#10 0x00007f9d758b1b9a in ?? () from /lib64/ld-linux-x86-64.so.2
# snip
```

Edit: Upgrading to g++ 11.1 did not help:
```
$ sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
$ sudo apt install -y g++-11
$ g++-11 --version
g++-11 (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ CXX=g++-11 pip install --no-cache -Iv horovod
$ rr record python -c 'import horovod.tensorflow'
rr: Saving execution to trace directory `..../home/.local/share/rr/python-13'.
Segmentation fault
```

### PR DESCRIPTION
**Pull request by khuey**
Fixes #3304

### CODE REVIEW

File: src/preload/overrides.c [hunk 1]
```diff
@@ -242,6 +242,12 @@ uid_t geteuid(void) {
 #endif
 }
 
+static void libstdcpp_not_found(void) {
+  logmsg("[rr] Interposition for libstdc++ called but symbol lookups into libstdc++ failed.\n"
```
Comment (yuyichao) [inline src/preload/overrides.c:246]: Does this have to be using syscallbuf code? I know this is in the error path already but this also has he potential of causing an assertion. Ref https://github.com/rr-debugger/rr/pull/3284

Comment (rocallahan) [reply src/preload/overrides.c:246]: Yeah I think we should use a dedicated write syscall here.
