### PR TITLE
Fixes #3182 - Overshooting sys calls

### LINKED ISSUE #3182: rr assertion failed when replaying record of gdb
Attempting to replay a record of gdb fails. The GDB version is the one pulled from the master branch of gdb's repo (`git clone git://sourceware.org/git/binutils-gdb.git`).

Discussion on Elements chat with @khuey revealed that earlier versions (10.1) succeeds and that it might have something to do with gdb setting a breakpoint and it not firing during the replay.

To reproduce the steps; build gdb and record gdb while doing these commands:

- start gdb and debug a binary
- set a breakpoint at line X
- run

The setting of the breakpoint is fine, It's when it runs it fails. The trace dump and stack trace dump:

```
Starting program: /home/cx/dev/opensource/gdb-regressions/29060-optimized-out/opt 
[FATAL /home/cx/dev/opensource/rr/src/ReplaySession.cc:667:check_pending_sig()] 
 (task 5103 (rec:3586) at time 3480)
 -> Assertion `false' failed to hold. Replaying `SIGNAL: SIGTRAP(det)': expecting tracee signal or trap, but instead at `munmap' (ticks: 231972)
Tail of trace dump:
{
  real_time:162.962384 global_time:3460, event:`SYSCALL: arch_prctl' (state:ENTERING_SYSCALL) tid:3586, ticks:219911
rax:0xffffffffffffffda rbx:0x7fffffffd9b0 rcx:0xffffffffffffffff rdx:0xffff80000828eeb0 rsi:0x7ffff7d70740 rdi:0x1002 rbp:0x0 rsp:0x7fffffffd8e0 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x7ffff7d70740 r13:0x1 r14:0x7ffff7ffe220 r15:0x0 rip:0x7ffff7fc9bff eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9e fs_base:0x0 gs_base:0x0
}
{
  real_time:162.962422 global_time:3461, event:`SYSCALL: arch_prctl' (state:EXITING_SYSCALL) tid:3586, ticks:219911
rax:0x0 rbx:0x7fffffffd9b0 rcx:0xffffffffffffffff rdx:0xffff80000828eeb0 rsi:0x7ffff7d70740 rdi:0x1002 rbp:0x0 rsp:0x7fffffffd8e0 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x7ffff7d70740 r13:0x1 r14:0x7ffff7ffe220 r15:0x0 rip:0x7ffff7fc9bff eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9e fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.962537 global_time:3462, event:`SYSCALL: set_tid_address' (state:ENTERING_SYSCALL) tid:3586, ticks:219912
rax:0xffffffffffffffda rbx:0x7fffffffd9b0 rcx:0xffffffffffffffff rdx:0x7ffff7d70740 rsi:0x7ffff7ffe030 rdi:0x7ffff7d70a10 rbp:0x0 rsp:0x7fffffffd8d8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x7ffff7d70740 r13:0x1 r14:0x7ffff7ffe220 r15:0x0 rip:0x7ffff7fe1f72 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xda fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.962576 global_time:3463, event:`SYSCALL: set_tid_address' (state:EXITING_SYSCALL) tid:3586, ticks:219912
rax:0xe02 rbx:0x7fffffffd9b0 rcx:0xffffffffffffffff rdx:0x7ffff7d70740 rsi:0x7ffff7ffe030 rdi:0x7ffff7d70a10 rbp:0x0 rsp:0x7fffffffd8d8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x7ffff7d70740 r13:0x1 r14:0x7ffff7ffe220 r15:0x0 rip:0x7ffff7fe1f72 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xda fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.962690 global_time:3464, event:`SYSCALL: set_robust_list' (state:ENTERING_SYSCALL) tid:3586, ticks:219912
rax:0xffffffffffffffda rbx:0x7fffffffd9b0 rcx:0xffffffffffffffff rdx:0x7ffff7d70740 rsi:0x18 rdi:0x7ffff7d70a20 rbp:0x0 rsp:0x7fffffffd8d8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x7ffff7d70740 r13:0x1 r14:0x7ffff7ffe220 r15:0x0 rip:0x7ffff7fe1fce eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x111 fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.962728 global_time:3465, event:`SYSCALL: set_robust_list' (state:EXITING_SYSCALL) tid:3586, ticks:219912
rax:0x0 rbx:0x7fffffffd9b0 rcx:0xffffffffffffffff rdx:0x7ffff7d70740 rsi:0x18 rdi:0x7ffff7d70a20 rbp:0x0 rsp:0x7fffffffd8d8 r8:0xffffffff r9:0x0 r10:0x22 r11:0x246 r12:0x7ffff7d70740 r13:0x1 r14:0x7ffff7ffe220 r15:0x0 rip:0x7ffff7fe1fce eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x111 fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.962838 global_time:3466, event:`INSTRUCTION_TRAP' tid:3586, ticks:219938
rax:0xce233f9c rbx:0x0 rcx:0x0 rdx:0xa1 rsi:0x7fffffffe0bd rdi:0x7ffff7ffe220 rbp:0x7fffffffdbd0 rsp:0x7fffffffd900 r8:0x7 r9:0x7fffffffe0bd r10:0x22 r11:0x246 r12:0x0 r13:0x1 r14:0x7ffff7ffe220 r15:0x7ffff7d70740 rip:0x7ffff7fccbca eflags:0x10202 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.962948 global_time:3467, event:`SYSCALL: mprotect' (state:ENTERING_SYSCALL) tid:3586, ticks:230080
rax:0xffffffffffffffda rbx:0x7ffff7d9ae38 rcx:0xffffffffffffffff rdx:0x1 rsi:0x4000 rdi:0x7ffff7f88000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7d79de0 r9:0x0 r10:0x7ffff7d9ae20 r11:0x246 r12:0x7ffff7d73000 r13:0x7ffff7d9ae20 r14:0x7ffff7f8c018 r15:0x7ffff7fc4530 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963000 global_time:3468, event:`SYSCALL: mprotect' (state:EXITING_SYSCALL) tid:3586, ticks:230080
rax:0x0 rbx:0x7ffff7d9ae38 rcx:0xffffffffffffffff rdx:0x1 rsi:0x4000 rdi:0x7ffff7f88000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7d79de0 r9:0x0 r10:0x7ffff7d9ae20 r11:0x246 r12:0x7ffff7d73000 r13:0x7ffff7d9ae20 r14:0x7ffff7f8c018 r15:0x7ffff7fc4530 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963117 global_time:3469, event:`SYSCALL: mprotect' (state:ENTERING_SYSCALL) tid:3586, ticks:230383
rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x1000 rdi:0x7ffff7fbc000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7fb2408 r9:0x7ffff7fb34a9 r10:0x0 r11:0x246 r12:0x7ffff7fb2a58 r13:0x7ffff7fbd050 r14:0x7ffff7fb2000 r15:0x7ffff7fc4000 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963169 global_time:3470, event:`SYSCALL: mprotect' (state:EXITING_SYSCALL) tid:3586, ticks:230383
rax:0x0 rbx:0x0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x1000 rdi:0x7ffff7fbc000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7fb2408 r9:0x7ffff7fb34a9 r10:0x0 r11:0x246 r12:0x7ffff7fb2a58 r13:0x7ffff7fbd050 r14:0x7ffff7fb2000 r15:0x7ffff7fc4000 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963286 global_time:3471, event:`SYSCALL: mprotect' (state:ENTERING_SYSCALL) tid:3586, ticks:230939
rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x1000 rdi:0x555555557000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7d79270 r9:0x7ffff7ea68f0 r10:0x0 r11:0x246 r12:0x0 r13:0x400000007 r14:0x555555554438 r15:0x7ffff7ffe220 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963338 global_time:3472, event:`SYSCALL: mprotect' (state:EXITING_SYSCALL) tid:3586, ticks:230939
rax:0x0 rbx:0x0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x1000 rdi:0x555555557000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7d79270 r9:0x7ffff7ea68f0 r10:0x0 r11:0x246 r12:0x0 r13:0x400000007 r14:0x555555554438 r15:0x7ffff7ffe220 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963449 global_time:3473, event:`INSTRUCTION_TRAP' tid:3586, ticks:230943
rax:0xce44bea4 rbx:0x0 rcx:0xffffffffffffffff rdx:0xa1 rsi:0x1000 rdi:0x555555557000 rbp:0x7fffffffdbd0 rsp:0x7fffffffd900 r8:0x7ffff7d79270 r9:0x7ffff7ea68f0 r10:0x0 r11:0x246 r12:0x0 r13:0xfffffffffffffff8 r14:0x7ffff7ffe220 r15:0x7ffff7d70740 rip:0x7ffff7fcc779 eflags:0x10246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963532 global_time:3474, event:`INSTRUCTION_TRAP' tid:3586, ticks:231306
rax:0xce494ae0 rbx:0x0 rcx:0x0 rdx:0xa1 rsi:0x7ffff7ff35dd rdi:0x7ffff7d9129f rbp:0x7fffffffdbd0 rsp:0x7fffffffd900 r8:0xffff r9:0x7 r10:0xfffffffffffffbb7 r11:0x4 r12:0x0 r13:0xfffffffffffffff8 r14:0x7ffff7ffe220 r15:0x7ffff7ffe220 rip:0x7ffff7fcce53 eflags:0x10206 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963619 global_time:3475, event:`SYSCALL: mprotect' (state:ENTERING_SYSCALL) tid:3586, ticks:231820
rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x2000 rdi:0x7ffff7ffb000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7d7ade8 r9:0x0 r10:0x7ffff7fc84b0 r11:0x246 r12:0x0 r13:0x7ffff7ffce20 r14:0x7ffff7fc8000 r15:0x7ffff7ffda48 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963671 global_time:3476, event:`SYSCALL: mprotect' (state:EXITING_SYSCALL) tid:3586, ticks:231820
rax:0x0 rbx:0x0 rcx:0xffffffffffffffff rdx:0x1 rsi:0x2000 rdi:0x7ffff7ffb000 rbp:0x7fffffffd8f0 rsp:0x7fffffffd7e8 r8:0x7ffff7d7ade8 r9:0x0 r10:0x7ffff7fc84b0 r11:0x246 r12:0x0 r13:0x7ffff7ffce20 r14:0x7ffff7fc8000 r15:0x7ffff7ffda48 rip:0x7ffff7fec43b eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xa fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963782 global_time:3477, event:`INSTRUCTION_TRAP' tid:3586, ticks:231822
rax:0xce5700e0 rbx:0xa1ce494ae0 rcx:0xffffffffffffffff rdx:0xa1 rsi:0x2000 rdi:0x7ffff7ffb000 rbp:0x7fffffffdbd0 rsp:0x7fffffffd900 r8:0x7ffff7d7ade8 r9:0x0 r10:0x7ffff7fc84b0 r11:0x246 r12:0x0 r13:0xfffffffffffffff8 r14:0x7ffff7ffe220 r15:0x7ffff7ffe220 rip:0x7ffff7fcce7d eflags:0x10246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963876 global_time:3478, event:`SYSCALL: prlimit64' (state:ENTERING_SYSCALL) tid:3586, ticks:231843
rax:0xffffffffffffffda rbx:0x1 rcx:0xffffffffffffffff rdx:0x0 rsi:0x3 rdi:0x0 rbp:0x7fffffffdbd0 rsp:0x7fffffffd8c8 r8:0x0 r9:0x1 r10:0x7fffffffd8d0 r11:0x246 r12:0x0 r13:0xfffffffffffffff8 r14:0x7ffff7ffe220 r15:0x7ffff7ffe220 rip:0x7ffff7e8c404 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12e fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.963921 global_time:3479, event:`SYSCALL: prlimit64' (state:EXITING_SYSCALL) tid:3586, ticks:231843
rax:0x0 rbx:0x1 rcx:0xffffffffffffffff rdx:0x0 rsi:0x3 rdi:0x0 rbp:0x7fffffffdbd0 rsp:0x7fffffffd8c8 r8:0x0 r9:0x1 r10:0x7fffffffd8d0 r11:0x246 r12:0x0 r13:0xfffffffffffffff8 r14:0x7ffff7ffe220 r15:0x7ffff7ffe220 rip:0x7ffff7e8c404 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12e fs_base:0x7ffff7d70740 gs_base:0x0
  { tid:3586, addr:0x7fffffffd8d0, length:0x10 }
}
{
  real_time:162.964060 global_time:3480, event:`SIGNAL: SIGTRAP(det)' tid:3586, ticks:231971
rax:0x7ffff7ffe100 rbx:0x7ffff7ffe100 rcx:0x7ffff7ffc020 rdx:0x7ffff7e03b20 rsi:0x0 rdi:0x0 rbp:0x7fffffffdbd0 rsp:0x7fffffffd900 r8:0x0 r9:0x1 r10:0x7ffff7fed330 r11:0x7ffff7fe37a0 r12:0x0 r13:0xfffffffffffffff8 r14:0x7ffff7ffe220 r15:0x7ffff7ffe220 rip:0x7ffff7fcc877 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7ffff7d70740 gs_base:0x0
}
{
  real_time:162.964133 global_time:3481, event:`SYSCALL: poll' (state:EXITING_SYSCALL) tid:3583, ticks:11465707
rax:0xfffffffffffffdfc rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0xffffffff rsi:0x4 rdi:0x55b0bcd0acf0 rbp:0xffffffff rsp:0x681ffdf0 r8:0x0 r9:0x55b0bcb9c140 r10:0x55b0bcb9b150 r11:0x246 r12:0x0 r13:0x7f5efcd5a086 r14:0x55b0bcd0acf0 r15:0x7f5efcd5a0a6 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x7 fs_base:0x7f5efce5cb40 gs_base:0x0
}
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x60)[0x56238b29fde6]
rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0xfb)[0x56238b096af7]
rr(+0x3ee8eb)[0x56238b0d18eb]
rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x63)[0x56238b0d1b91]
rr(_ZN2rr13ReplaySession17check_pending_sigEPNS_10ReplayTaskE+0x16f)[0x56238b1d2c95]
rr(_ZN2rr13ReplaySession16continue_or_stepEPNS_10ReplayTaskERKNS0_15StepConstraintsENS_12TicksRequestENS_13ResumeRequestE+0x1f0)[0x56238b1d309a]
rr(_ZN2rr13ReplaySession28emulate_deterministic_signalEPNS_10ReplayTaskEiRKNS0_15StepConstraintsE+0x108)[0x56238b1d54ba]
rr(_ZN2rr13ReplaySession18try_one_trace_stepEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x174)[0x56238b1d7810]
rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x1d7)[0x56238b1d904f]
rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandEl+0x138)[0x56238b1f9b4c]
rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0x601)[0x56238b093741]
rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x588)[0x56238b095bb4]
rr(+0x4ea566)[0x56238b1cd566]
rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x41f)[0x56238b1ce085]
rr(main+0x278)[0x56238b2bbe64]
/lib/x86_64-linux-gnu/libc.so.6(+0x29fd0)[0x7f9a70ccefd0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d)[0x7f9a70ccf07d]
rr(_start+0x25)[0x56238afdf745]
=== End rr backtrace
```

### PR DESCRIPTION
**Pull request by theIDinside**
This patch fixes the parsing of the thread ID from
the proc filesystem. Man pages for proc on linux says;
There are two paths for a running thread that is not a
thread group leader;
/proc/[tid]/.. and /proc/[pid]/task/[tid]/...

rr currently does not register to watch on the latter.

The parsing of the tid is lifted into it's own function in util.h/cc,
which ProcMemMonitor and ProcFdDirMonitor calls.

Recording and replaying (issue #3182 was specifically for GDB)
is tested and with this patch, rr does not fail.

Test cases for /proc/pid/task/tid written by @khuey

### CODE REVIEW

File: src/ProcFdDirMonitor.cc [hunk 1]
```diff
@@ -17,19 +17,12 @@ namespace rr {
...
-  int ends_with_slash = (pathname.back() == '/');
-  if (pathname.substr(0, 6) == string("/proc/") &&
-      pathname.substr(pathname.size() - 3 - ends_with_slash, 3) ==
-          string("/fd")) {
-    string s = pathname.substr(6, pathname.size() - 9 - ends_with_slash);
-    char* end;
-    int tid = strtol(s.c_str(), &end, 10);
-    if (!*end) {
+  int tid = parse_tid_from_proc_path(pathname, "/fd");
+  if(tid > 0) {
```
Comment (khuey) [inline src/ProcFdDirMonitor.cc:21]: Nit: space between if and ( is our style.

File: src/ProcMemMonitor.cc [hunk 2]
```diff
@@ -17,17 +17,12 @@ namespace rr {
...
   // XXX this makes some assumptions about namespaces... Probably fails
   // if |t| is not the same pid namespace as rr
-  if (pathname.substr(0, 6) == string("/proc/") &&
-      pathname.substr(pathname.size() - 4, 4) == string("/mem")) {
-    string s = pathname.substr(6, pathname.size() - 10);
-    char* end;
-    int tid = strtol(s.c_str(), &end, 10);
-    if (!*end) {
+  int tid = parse_tid_from_proc_path(pathname, "/mem");
+  if(tid > 0) {
```
Comment (khuey) [inline src/ProcMemMonitor.cc:21]: here too

File: src/util.cc [hunk 3]
```diff
@@ -2404,4 +2404,36 @@ bool coredumping_signal_takes_down_entire_vm() {
...
+      pathname.size() - property.size() - (pathname.back() == '/');
+  if (pathname.substr(prop_begin, property.size()) == property) {
+    const auto task = "task/"s;
+    const auto pos = pathname.find(task);
+    if (pos == std::string::npos) {
+      auto tid_length = pathname.find(property) - proc_length;
+      const auto s = pathname.substr(proc_length, tid_length);
+      char* end;
+      const int tid = strtol(s.c_str(), &end, 10);
+      if (!*end) {
```
Comment (khuey) [inline src/util.cc:2423]: I'm pretty sure strtol sets end to the input pointer on failure[0], not to null. Please check that (e.g. by strtol()ing a letter) and change this code if necessary.

[0] https://c-for-dummies.com/blog/?p=3671

File: src/util.cc [hunk 4]
```diff
@@ -2404,4 +2404,36 @@ bool coredumping_signal_takes_down_entire_vm() {
...
+        return tid;
+      }
+    } else {
+      const auto prop_pos = pathname.find(property);
+      const auto s =
+          pathname.substr(pos + task.size(), prop_pos - (pos + task.size()));
+      char* end;
+      const int tid = strtol(s.c_str(), &end, 10);
+      if (!*end) {
```
Comment (khuey) [inline src/util.cc:2432]: likewise

**Review by khuey — CHANGES_REQUESTED** [review]
Looks pretty good. Some relatively minor comments.

Please change the first line of the commit message to something like "Support /proc/[pid]/task/[tid]/[mem|fd]" (the rest of it is fine).

`git commit --amend` and then `git push -f` ought to get you there.

File: src/util.cc (hunk 3 above)
Comment (theIDinside) [reply src/util.cc:2423]: You're right, it does. I re-used the previous code that was there. Technically, to check "ok'ness" the check could be 
```cpp
const auto s = pathname.substr(proc_length);
char* end;
const int tid = strtol(s.c_str(), &end, 10); 
if (end == property.c_str()) { ... }
```

Because this way, the "failure" will always be `== property` since the pre-conditions is that the pathname always end with the "property". I'll play around and see what fits best.

**Comment by khuey** [comment]
lgtm, thanks

**Comment by DilumAluthge** [comment]
The CI failure is due to a change in our CI infrastructure. I'll make a PR to fix it.

**Comment by DilumAluthge** [comment]
> The CI failure is due to a change in our CI infrastructure. I'll make a PR to fix it.

#3186
