### PR TITLE
More fully restore kernel state in AutoRemoteSyscalls

### LINKED ISSUE #3141: Replay divergence involving futex
Opening this issue to track the rr replay divergence reported in https://github.com/JuliaLang/julia/issues/44916.
The trace is julia-0 from https://buildkite.com/julialang/julia-master/builds/10893#b220a3a6-0f54-45ff-bc16-1e7ea2650686.

`replay -a` gives:
```
[ERROR /home/keno/rr/src/Registers.cc:295:maybe_print_reg_mismatch()] rdx 0 != 0x902 (replaying vs. recorded)
[ERROR /home/keno/rr/src/Registers.cc:295:maybe_print_reg_mismatch()] rsi 0x80 != 0x7fa08d44e59e (replaying vs. recorded)
[ERROR /home/keno/rr/src/Registers.cc:295:maybe_print_reg_mismatch()] rdi 0x7fa073f1b8e4 != 0xffffff9c (replaying vs. recorded)
[ERROR /home/keno/rr/src/Registers.cc:295:maybe_print_reg_mismatch()] rbp 0xca != 0x902 (replaying vs. recorded)
[ERROR /home/keno/rr/src/Registers.cc:295:maybe_print_reg_mismatch()] r12 0x3 != 0x7fa08d44e59e (replaying vs. recorded)
[ERROR /home/keno/rr/src/Registers.cc:295:maybe_print_reg_mismatch()] r13 0x7fa073f1b890 != 0x3 (replaying vs. recorded)
[ERROR /home/keno/rr/src/Registers.cc:295:maybe_print_reg_mismatch()] orig_rax 0xca != 0x101 (replaying vs. recorded)
[FATAL /home/keno/rr/src/Registers.cc:405:compare_register_files()]
 (task 15802 (rec:3747) at time 2733407)
 -> Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:556688/557187)
```

Note in particular that the event in questions is:
```
{
  real_time:46277558.967971 global_time:2733406, event:`SYSCALL: restart_syscall' (state:EXITING_SYSCALL) tid:3747, ticks:556688
rax:0xfffffffffffffe00 rbx:0x7fa071910fa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x80 rdi:0x7fa073f1b8e4 rbp:0xca rsp:0x7fa071910de0 r8:0x0 r9:0x8ce09d8 r10:0x0 r11:0x246 r12:0x3 r13:0x7fa073f1b890 r14:0x0 r15:0x7fa073f1b8e4 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fa072111700 gs_base:0x0
}
{
  real_time:46277558.968086 global_time:2733407, event:`SYSCALL: openat' (state:ENTERING_SYSCALL) tid:3747, ticks:557187
rax:0xffffffffffffffda rbx:0x7fa071910fa0 rcx:0xffffffffffffffff rdx:0x902 rsi:0x7fa08d44e59e rdi:0xffffff9c rbp:0x902 rsp:0x7fa071910de0 r8:0x0 r9:0x8ce09d8 r10:0x0 r11:0x246 r12:0x7fa08d44e59e r13:0x3 r14:0x0 r15:0x7fa073f1b8e4 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x101 fs_base:0x7fa072111700 gs_base:0x0
}
```

So it looks like during replay, we're incurring an immediate restart of the futex syscall while during the record we were able to exit the loop and move on. I'll investigate what the futex in question is. Note that the original bug report here was about unexpected futex behavior, so it's possible there's something strange afoot.

### PR DESCRIPTION
**Pull request by Keno**
Fix #3141 and #3147. In essence the issue is that AutoRemoteSyscall needs to work harder to actually restore the state that it was in at the start. Details are in the individual commit messages.

### CODE REVIEW

**Comment by Keno** [comment]
@rocallahan Have a look at this. My theory in https://github.com/rr-debugger/rr/issues/3141#issuecomment-1095438001 turned out to be basically correct (or at least I was able to reproduce the issue with the included test by forcing this sequence).

**Comment by DilumAluthge** [comment]
Closes https://github.com/JuliaLang/julia/issues/44916, I assume?

**Comment by Keno** [comment]
> Closes [JuliaLang/julia#44916](https://github.com/JuliaLang/julia/issues/44916), I assume?

Yes, once we pick it up and deploy it.

**Comment by khuey** [comment]
Excellent catch. The comments could use another pass for grammar issues.

**Comment by DilumAluthge** [comment]
CI timed out; the `TMPDIR` was uploaded. I've triggered a retry of the failed job.

**Comment by DilumAluthge** [comment]
The retry failed with https://github.com/rr-debugger/rr/issues/3129; the `TMPDIR` was uploaded.

I've triggered another retry.

File: src/preload/rrcalls.h [hunk 1]
```diff
@@ -84,3 +84,8 @@
  * cases between the time slice signal and other rr behavior.
  */
 #define SYS_rrcall_arm_time_slice (RR_CALL_BASE + 10)
+/**
+ * Requests that rr not schedule a given thread. Used to test
+ * interactions with rr's scheduler
+ */
+#define SYS_rrcall_freeze_tid (RR_CALL_BASE + 11)
```
Comment (rocallahan) [inline src/preload/rrcalls.h:91]: Please document the parameters (tid) and exactly what this means. Is the thread never scheduled again?

Also, in many tests I've achieved similar results by making the "frozen" thread lower priority than other threads. Does that not work here for some reason?

File: src/AutoRemoteSyscalls.cc [hunk 2]
```diff
@@ -131,6 +132,18 @@ AutoRemoteSyscalls::AutoRemoteSyscalls(Task* t,
     // AutoRemoteSyscall (see below).
     need_sigpending_renable = true;
   }
+  if (t->session().is_recording()) {
+    RecordTask *rt = static_cast<RecordTask*>(t);
+    if (rt->schedule_frozen) {
```
Comment (rocallahan) [inline src/AutoRemoteSyscalls.cc:137]: Why are we only doing this for `schedule_frozen`? Wouldn't it make sense to do this for all signals?

File: src/preload/rrcalls.h (hunk 1 above)
Comment (Keno) [reply src/preload/rrcalls.h:91]: Will add documentation. The parameters are (tid, enable). rr will refuse to schedule the thread until called again with enable=0.

The reason for the rrcall is that I need different scheduling behavior between the kernel and rr's scheduler. I need the kernel to schedule it relatively soon (to wake it up while the signal is still pending and proceed to the exit stop), with enough headway for rr to notice that the thread was stopped, but I don't want rr to schedule it again until we've dequeued all the signals from the shared queue.

File: src/AutoRemoteSyscalls.cc (hunk 2 above)
Comment (Keno) [reply src/AutoRemoteSyscalls.cc:137]: Yes, it makes sense for all tasks, but it does incur two additional syscalls (though if there are actually pending signals, it's much cheaper than what we need to do to handle that case). Usually it's not really a problem to dequeue these signals, we'll just stash them and get back to them later, but in this case, dequeing the signal on the thread is a problem, because we expect the main thread to get to them first.

File: src/record_syscall.cc [hunk 3]
```diff
@@ -4984,6 +4984,31 @@ static Switchable rec_prepare_syscall_arch(RecordTask* t,
       return PREVENT_SWITCH;
     }
 
+    case SYS_rrcall_freeze_tid: {
+      Registers r = t->regs();
+      bool arguments_are_zero = true;
+      for (int i = 3; i <= 6; ++i) {
+        arguments_are_zero &= r.arg(i) == 0;
```
Comment (rocallahan) [inline src/record_syscall.cc:4991]: Looks like you don't do anything with this value?

**Review by rocallahan — CHANGES_REQUESTED** [review]

**Comment by Keno** [comment]
@rocallahan is this good to go?

**Comment by rocallahan** [comment]
Sure, sorry about the delay.
